export const WeatherIcons = {
    "Cloudy": require('../weatherIcons/cloud-light.png'),
    "Sunny":require('../weatherIcons/sun-light.png'),
    "Mostly Sunny":require('../weatherIcons/sun-light.png'),
    "Partly Sunny":require('../weatherIcons/partial-cloudy-light.png'),
    "Intermittent Clouds":require('../weatherIcons/mostly-cloud-light.png'),
    "Hazy Sunshine":require('../weatherIcons/sun-light.png'),
    "Mostly Cloudy":require('../weatherIcons/mostly-cloud-light.png'),
    "Dreary (Overcast)":require('../weatherIcons/mostly-cloudy-light.png'),
    "Fog":require('../weatherIcons/mostly-cloudy-light.png'),
    "Showers":require('../weatherIcons/rain-light.png'),
    "Mostly Cloudy w/ Showers":require('../weatherIcons/rainyday-light.png'),
    "Partly Sunny w/ Showers":require('../weatherIcons/rainyday-light.png'),
    "T-Storms":require('../weatherIcons/thunderstorm-light.png'),
    "Mostly Cloudy w/ T-Storms":require('../weatherIcons/thunderstorm-light.png'),
    "Partly Sunny w/ T-Storms":require('../weatherIcons/thunderstorm-light.png'),
    "Rain":require('../weatherIcons/rain-light.png'),
    "Flurries":require('../weatherIcons/snow-light.png'),
    "Mostly Cloudy w/ Flurries":require('../weatherIcons/snow-light.png'),
    "Partly Sunny w/ Flurries":require('../weatherIcons/snow-light.png'),
    "Snow":require('../weatherIcons/heavy-snowfall-light.png'),
    "Mostly Cloudy w/ Snow":require('../weatherIcons/heavy-snowfall-light.png'),
    "Ice":require('../weatherIcons/heavy-snowfall-light.png'),
    "Sleet":require('../weatherIcons/snow-light.png'),
    "Freezing Rain":require('../weatherIcons/snow-light.png'),
    "Rain and Snow":require('../weatherIcons/snow-light.png'),
    "Hot":require('../weatherIcons/sun-light.png'),
    "Cold":require('../weatherIcons/snow-light.png'),
    "Windy":require('../weatherIcons/heavy-wind-light.png'),
    "Clear":require('../weatherIcons/sun-light.png'),
    "Mostly Clear":require('../weatherIcons/sun-light.png'),
    "Partly Cloudy":require('../weatherIcons/partial-cloudy-light.png'),
    "Intermittent Clouds":require('../weatherIcons/mostly-cloudy-light.png'),
    "Hazy Moonlight":require('../weatherIcons/full-moon-light.png'),
    "Mostly Cloudy":require('../weatherIcons/mostly-cloudy-light.png'),
    "Partly Cloudy w/ Showers":require('../weatherIcons/rain-light.png'),
    "Mostly Cloudy w/ Showers":require('../weatherIcons/rain-light.png'),
    "Partly Cloudy w/ T-Storms":require('../weatherIcons/thunderstorm-light.png'),
    "Mostly Cloudy w/ T-Storms":require('../weatherIcons/thunderstorm-light.png'),
    "Mostly Cloudy w/ Flurries":require('../weatherIcons/snow-light.png'),
    "Mostly Cloudy w/ Snow":require('../weatherIcons/snow-light.png')
};

